name: in_app_update_me
description: A comprehensive Flutter plugin for in-app updates supporting both Android and iOS with direct update capabilities, flexible updates, and force update handling.
version: 1.1.1
homepage: https://github.com/atishpaul/in_app_update_me
repository: https://github.com/atishpaul/in_app_update_me
issue_tracker: https://github.com/atishpaul/in_app_update_me/issues
documentation: https://github.com/atishpaul/in_app_update_me#readme

topics:
  - in-app-update
  - flutter-plugin
  - android-ios
  - force-update
  - flexible-updates

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  http: ^1.1.0
  path_provider: ^2.1.1
  archive: ^3.4.9
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.flenco.in_app_update_me
        pluginClass: InAppUpdateMePlugin
      ios:
        pluginClass: InAppUpdateMePlugin